import type {Metadata} from "next";
import "../globals.css";
import NavbarComponent from "@/components/navbar/NavbarComponent";
import {Suspense} from "react";
import Loading from "@/app/(user)/loading";
import {inter, suwannaphum, localCustomFont} from "@/app/(user)/fonts";

export const metadata: Metadata = {
    title: "My Next App",
    description: "Generated by create next app",
    openGraph: {
        title: "My next.js App",
        description: "Testing using metadata in nextjs",
        // images:"https://tse2.mm.bing.net/th/id/OIG3.EWlw7z9GbyIZqfKlxd5L?pid=ImgGn"
    }
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${inter.variable} ${suwannaphum.variable} ${localCustomFont.variable}`}>
        <NavbarComponent/>
        <Suspense fallback={<Loading/>}>{children}</Suspense>
        </body>
        </html>
    );
}
